project_id = "qgvloiecyvqbxeplfzwv"

[functions.create-agent]
verify_jwt = false

[functions.send-agency-invitation]
verify_jwt = false

[functions.notify-favorite]
verify_jwt = false

[functions.send-property-statistics]
verify_jwt = false
